"https://dhh1128.github.io/coia":
  - category: Specifications
  - title: Conventions for Opaque Identifier Aliases (COIA)
  - date: 2025-08-28
"https://dhh1128.github.io/canonical-quoted-text":
  - category: Specifications
  - title: Canonical Quoted Text
  - date: 2023-06-01
"https://dhh1128.github.io/cfa":
  - category: Specifications
  - title: Cross-File Associations
  - date: 2022-09-01
"https://dhh1128.github.io/vvp":
  - category: Specifications
  - title: Verifiable Voice Protocol (VVP)
  - date: 2025-02-01