title: Daniel Hardman's Papers
description: scholarly and technical writings on various topics
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
url: "https://dhh1128.github.io"
show_downloads: false
include:
  - robots.txt
  - LICENSE
author:
  name: "Daniel Hardman"
  twitter: "dhh1128"
  email: "daniel.hardman@gmail.com"