name: check links in markdown files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lychee link checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose